from enum import StrEnum


class Role(StrEnum):
    WEREWOLF = "WEREWOLF"
    SEER = "SEER"
    WITCH = "WITCH"
    VILLAGER = "VILLAGER"


class Faction(StrEnum):
    WEREWOLF = "WEREWOLF"
    GOOD = "GOOD"


class Phase(StrEnum):
    LOBBY = "LOBBY"
    ROLE_REVEAL = "ROLE_REVEAL"
    NIGHT_START = "NIGHT_START"
    NIGHT_WOLF = "NIGHT_WOLF"
    NIGHT_SEER = "NIGHT_SEER"
    NIGHT_WITCH = "NIGHT_WITCH"
    NIGHT_RESOLVE = "NIGHT_RESOLVE"
    DAY_ANNOUNCE = "DAY_ANNOUNCE"
    DAY_DISCUSSION = "DAY_DISCUSSION"
    DAY_VOTE = "DAY_VOTE"
    DAY_PK_DISCUSSION = "DAY_PK_DISCUSSION"
    DAY_PK_VOTE = "DAY_PK_VOTE"
    DAY_EXILE = "DAY_EXILE"
    WIN_CHECK = "WIN_CHECK"
    GAME_END = "GAME_END"


class EventType(StrEnum):
    ROOM_JOINED = "ROOM_JOINED"
    READY_CHANGED = "READY_CHANGED"
    ROLE_ASSIGNED = "ROLE_ASSIGNED"
    ROLE_CONFIRMED = "ROLE_CONFIRMED"
    PHASE_CHANGED = "PHASE_CHANGED"
    WOLF_NOMINATION_RECORDED = "WOLF_NOMINATION_RECORDED"
    WOLF_TARGET_LOCKED = "WOLF_TARGET_LOCKED"
    SEER_CHECKED = "SEER_CHECKED"
    WITCH_ACTION_RECORDED = "WITCH_ACTION_RECORDED"
    PLAYERS_DIED = "PLAYERS_DIED"
    SPEECH_RECORDED = "SPEECH_RECORDED"
    SPEECH_PASSED = "SPEECH_PASSED"
    VOTE_RECORDED = "VOTE_RECORDED"
    ABSTAIN_RECORDED = "ABSTAIN_RECORDED"
    VOTE_ROUND_RESOLVED = "VOTE_ROUND_RESOLVED"
    PLAYER_EXILED = "PLAYER_EXILED"
    NO_EXILE = "NO_EXILE"
    TIMEOUT_APPLIED = "TIMEOUT_APPLIED"
    HOST_PAUSED = "HOST_PAUSED"
    HOST_RESUMED = "HOST_RESUMED"
    GAME_ENDED = "GAME_ENDED"


class CommandType(StrEnum):
    JOIN_ROOM = "JOIN_ROOM"
    SET_READY = "SET_READY"
    CONFIRM_ROLE = "CONFIRM_ROLE"
    WOLF_NOMINATE_KILL = "WOLF_NOMINATE_KILL"
    SEER_INSPECT = "SEER_INSPECT"
    WITCH_USE_ANTIDOTE = "WITCH_USE_ANTIDOTE"
    WITCH_USE_POISON = "WITCH_USE_POISON"
    WITCH_SKIP = "WITCH_SKIP"
    SPEAK = "SPEAK"
    PASS_SPEECH = "PASS_SPEECH"
    VOTE = "VOTE"
    ABSTAIN = "ABSTAIN"
    RECONNECT = "RECONNECT"
    HOST_PAUSE = "HOST_PAUSE"
    HOST_RESUME = "HOST_RESUME"
    HOST_PATCH = "HOST_PATCH"
    HOST_REWIND_TO_SNAPSHOT = "HOST_REWIND_TO_SNAPSHOT"
    HOST_FORCE_TEMPLATE = "HOST_FORCE_TEMPLATE"
